In [1]:
#B22DCCN476 - Đỗ Ngọc Lâm
#Cell [1]. [Import NumPy]

import numpy as np

print("NumPy version:", np.__version__)


NumPy version: 2.2.6


In [2]:
#B22DCCN476 - Đỗ Ngọc Lâm
#Cell [2]. [Scalar – Tensor 0 chiều]

# Scalar (0D tensor)
a = np.array(5)

print("a =", a)
print("Số chiều (ndim):", a.ndim)
print("Shape:", a.shape)


a = 5
Số chiều (ndim): 0
Shape: ()


In [3]:
#B22DCCN476 - Đỗ Ngọc Lâm
#Cell [3]. [Vector – Tensor 1 chiều]

# Vector (1D tensor)
v = np.array([1, 2, 3, 4])

print("v =", v)
print("Số chiều (ndim):", v.ndim)
print("Shape:", v.shape)


v = [1 2 3 4]
Số chiều (ndim): 1
Shape: (4,)


In [4]:
#B22DCCN476 - Đỗ Ngọc Lâm
#Cell [4]. [Matrix – Tensor 2 chiều]

# Matrix (2D tensor)
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("m =\n", m)
print("Số chiều (ndim):", m.ndim)
print("Shape:", m.shape)


m =
 [[1 2 3]
 [4 5 6]]
Số chiều (ndim): 2
Shape: (2, 3)


In [5]:
#B22DCCN476 - Đỗ Ngọc Lâm
#Cell [5]. [Tensor 3 chiều – ví dụ ảnh xám]

# Tensor 3D: (số ảnh, chiều cao, chiều rộng)
images = np.random.randint(
    0, 256,
    size=(2, 4, 4),
    dtype=np.uint8
)

print("images =\n", images)
print("Số chiều (ndim):", images.ndim)
print("Shape:", images.shape)


images =
 [[[ 68 231  26  29]
  [  5 183  39 175]
  [127  19  69 246]
  [149 205 139  19]]

 [[247 210 178 214]
  [141  17  16 215]
  [ 66 119 162 153]
  [113 222  49 203]]]
Số chiều (ndim): 3
Shape: (2, 4, 4)


In [6]:
#B22DCCN476 - Đỗ Ngọc Lâm
#Cell [6]. [Tensor 4 chiều – ảnh màu (batch, H, W, C)]

# Tensor 4D: batch ảnh RGB
rgb_images = np.random.randint(
    0, 256,
    size=(2, 4, 4, 3),
    dtype=np.uint8
)

print("Shape:", rgb_images.shape)
print("Số chiều (ndim):", rgb_images.ndim)


Shape: (2, 4, 4, 3)
Số chiều (ndim): 4


In [7]:
#B22DCCN476 - Đỗ Ngọc Lâm
#Cell [7]. [Phép toán trên tensor (element-wise)]

x = np.array([[1, 2],
              [3, 4]])

y = np.array([[10, 20],
              [30, 40]])

print("x + y =\n", x + y)
print("x * y =\n", x * y)


x + y =
 [[11 22]
 [33 44]]
x * y =
 [[ 10  40]
 [ 90 160]]


In [8]:
#B22DCCN476 - Đỗ Ngọc Lâm
#Cell [8]. [Broadcasting – tính chất quan trọng của tensor]

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print("a shape:", a.shape)
print("b shape:", b.shape)
print("a + b =\n", a + b)


a shape: (2, 3)
b shape: (3,)
a + b =
 [[11 22 33]
 [14 25 36]]
